---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    netbird_skip_login: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  tasks:
    - name: Verify that Netbird is installed
      ansible.builtin.command:
        cmd: netbird version
      changed_when: false
