---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Wait for system to be ready
      ansible.builtin.wait_for:
        timeout: 10

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Verify internet connectivity
      ansible.builtin.uri:
        url: https://www.google.com
        method: GET
        status_code: [200, 301, 302]
      register: internet_check
      until: internet_check is success
      retries: 5
      delay: 5
